// app/layout.js
import './globals.css'; // Ensure global styles are applied

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Import the Roboto font */}
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap"
        />
      </head>
      <body className="roboto-font">
        {children}
      </body>
    </html>
  );
}


